import json
from typing import Optional
from langchain_core.messages import SystemMessage, HumanMessage
from eos.domain.contracts.visual_proposal import VisualProposal
from eos.domain.contracts.editorial_brief import EditorialBrief
from eos.domain.contracts.creative_direction import CreativeDirection
from eos.domain.contracts.image_asset import ImageAsset
from eos.domain.contracts.rendered_code import RenderedCode
from eos.infrastructure.llm_router import AgentRole
from eos.infrastructure.context_loader import MarkdownContextLoader
from eos.infrastructure.structured_llm_adapter import StructuredLLMAdapter

class CoderAgent:
    """
    Agente Coder do EOS (EOS-011).
    Responsável por transformar a Proposta Visual em código HTML estrito,
    utilizando apenas o tokens.css e obedecendo o purismo editorial.
    """
    
    def __init__(self):
        self.system_prompt = MarkdownContextLoader.load("Coder Agent")
        self.adapter = StructuredLLMAdapter(AgentRole.CODER)
        
    def run(
        self, 
        proposal: VisualProposal, 
        brief: EditorialBrief, 
        direction: CreativeDirection, 
        image: Optional[ImageAsset] = None
    ) -> RenderedCode:
        
        image_url = image.image_url if image else ""
        
        human_msg = f"""
        # Conteúdo Editorial
        Tópico: {brief.topic}
        Objetivo: {brief.objective}
        Legenda Sugerida: {direction.suggested_caption}
        
        # Mídia Base
        Imagem URL: {image_url}
        
        # Proposta Visual
        Grid e Estrutura:
        {proposal.grid_structure}
        
        Constraints: You MUST write a <style> block in the <head> of the HTML defining all the layout classes you use (e.g. .poster-grid, .monolith-block). Use the variables from tokens.css (like var(--color-surface)) inside your <style> block. The image must be visible and properly styled.
        Você deve gerar um HTML completo, responsivo para 1080x1350, incorporando o conteúdo editorial, a imagem (como background ou tag img estilizada) e as regras CSS necessárias no head."""
        
        messages = [
            SystemMessage(content=self.system_prompt),
            HumanMessage(content=human_msg)
        ]
        
        fallback = RenderedCode(
            html_content=f"<article class='hh-layer-structure'><h1>{brief.topic}</h1></article>",
            css_tokens_used=["hh-layer-structure"],
            notes="Basic markup generated by fallback."
        )
        
        return self.adapter.invoke(messages, RenderedCode, fallback)
