import json
from langchain_core.messages import SystemMessage, HumanMessage
from eos.domain.contracts.visual_proposal import VisualProposal
from eos.domain.contracts.rendered_code import RenderedCode
from eos.infrastructure.llm_router import ModelRouter, AgentRole
from eos.infrastructure.context_loader import MarkdownContextLoader

class CoderAgent:
    """
    Agente Coder do EOS (EOS-011).
    Responsável por transformar a Proposta Visual em código HTML estrito,
    utilizando apenas o tokens.css e obedecendo o purismo editorial.
    """
    
    def __init__(self):
        self.system_prompt = MarkdownContextLoader.load("Coder Agent")
        self.llm = ModelRouter.get_model_for_role(AgentRole.CODER)
        
    def run(self, proposal: VisualProposal) -> RenderedCode:
        human_msg = f"""
        Visual Proposal:
        {proposal.grid_structure}
        
        Constraints: No inline CSS, no frameworks. Use ONLY tokens.css abstractions.
        """
        
        messages = [
            SystemMessage(content=self.system_prompt),
            HumanMessage(content=human_msg)
        ]
        
        response = self.llm.invoke(messages)
        
        try:
            if hasattr(response, 'content') and "{" in response.content:
                content = response.content
                json_str = content[content.find("{"):content.rfind("}")+1]
                data = json.loads(json_str)
                return RenderedCode(**data)
            elif isinstance(response, dict):
                return RenderedCode(**response)
        except Exception:
            pass
        
        # Fallback de segurança
        return RenderedCode(
            html_content="<article class='hh-layer-structure'><h1>Title</h1></article>",
            css_tokens_used=["hh-layer-structure"],
            notes="Basic markup generated by fallback."
        )
